url: https://pubinv.github.io/tetrahelix
repourl: https://github.com/PubInv/tetrahelix
projecttitle: "Untwisting the Tetrahelix"
featuretitle: "Untwisting the Tetrahelix"
featurelink: https://pubinv.github.io/tetrahelix